version: "3.9" 
services:
  web:
    build: app
    volumes: 
      - ./app/lib:/app/lib
      - ./app/priv:/app/priv
      - ./app/config:/app/config
      - ./app/assets:/app/assets
      - ./app/test:/app/test
    ports:
      - "8000:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://localhost/ || exit 1"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  db:
    image: postgres:14.2
    environment:
      - POSTGRES_PASSWORD=wally
    user:
      postgres
    ports:
      - "8001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5